# Generated by Django 4.1.2 on 2022-10-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
