# Generated by Django 4.1.2 on 2022-10-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_number_of_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
