# Generated by Django 4.1.2 on 2022-10-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_user_number_of_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instruments_teach',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
